### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by doldolOuO** [ltwu6/cross-pcc#3]
Hello, could you provide ground-truth point clouds of training dataset? Because I want to use the dataset you made for multi-modal point cloud completion in supervised manner.

**Comment by ltwu6** [comment]
Hi, we have uploaded the ground-truth data of the training set to Google Drive. You can download it by clicking on the link<https://drive.google.com/drive/folders/1BQg9r6RT0xZ3VZzc0NswiEGGVvE3FwD4?usp=sharing> we provided in this repository.
________________________________
发件人: Chenghao Fang ***@***.***>
发送时间: 2024年5月7日 15:56
收件人: ltwu6/cross-pcc ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Ext] [ltwu6/cross-pcc] Training dataset (Issue #3)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Hello, could you provide ground-truth point clouds of training dataset? Because I want to use the dataset you made for multi-modal point cloud completion in supervised manner.

―
